# Generated by Django 4.0.5 on 2022-08-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='favorite_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
