# Generated by Django 4.0.5 on 2022-08-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_favoritelist_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='favorite_product',
            field=models.CharField(max_length=9223372036854775807),
        ),
    ]
